# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version(">=1.9")

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "minimal/xenial64"
  config.vm.hostname = "docker-ansible"

  # Configure virtual hardware
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Name in VirtualBox GUI
    vb.name = "docker-ansible"
    # Customize the amount of memory on the VM
    vb.memory = "1024"
    # Customize CPUs
    vb.cpus = 1
    # Enable host's resolver as a DNS proxy in NAT mode
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Do not update virtual box guest additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  
  # Provisioning
  config.vm.provision "basics", type: "shell", privileged: true, inline: <<-SHELL
    apt-get update
    apt-get install -y sshpass python-pip
    pip install --upgrade pyvmomi docker-py ansible==2.4.2.0
  SHELL

  config.vm.provision "test_ansible", type: "ansible_local" do |ansible|
    ansible.install = false
    ansible.verbose = false
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "helloworld.yml"
    ansible.inventory_path = "inventories/inventory.ini"
    ansible.limit = "my-server"
  end

  config.vm.provision "setup_docker", run: "once", type: "ansible_local" do |ansible|
    ansible.install = false
    ansible.verbose = false
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "setup.yml"
    ansible.inventory_path = "inventories/inventory.ini"
    ansible.limit = "my-server"
  end
   
end
