# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version(">=1.9")

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "minimal/xenial64"

  # Update virtual box guest additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = true
  end
  
  # Configure virtual hardware
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM
    vb.memory = "2048"
    # Customize CPUs
    vb.cpus = 1
    # Enable linked clones
    vb.linked_clone = true
    # Enable host's resolver as a DNS proxy in NAT mode
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  es_cluster_nodes = "192.168.56.11,192.168.56.12,192.168.56.13"

  (1..3).each do |i|
    config.vm.define "host#{i}" do |node|

      # Node settings
      node.vm.hostname = "elastic-#{i}"
      node.vm.network "private_network", ip: "192.168.56.1#{i}"
      
      # VirtualBox settings
      node.vm.provider "virtualbox" do |vb|
        vb.name = "elastic-#{i}"
      end

      # Provisioning
      node.vm.provision "basics", type: "shell", privileged: true, inline: <<-SHELL
        export DEBIAN_FRONTEND=noninteractive
		wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        apt-get install -y apt-transport-https
        echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list
        apt-get update
        apt-get install -y openjdk-8-jre elasticsearch
        /bin/systemctl daemon-reload
        /bin/systemctl enable elasticsearch.service
      SHELL

      node.vm.provision "es", type: "shell", privileged: true, inline: <<-SHELL
        rm /etc/elasticsearch/elasticsearch.yml
        echo "path.data: /var/lib/elasticsearch" >> /etc/elasticsearch/elasticsearch.yml
        echo "path.logs: /var/log/elasticsearch" >> /etc/elasticsearch/elasticsearch.yml
        echo "network.host: 192.168.56.1#{i}" >> /etc/elasticsearch/elasticsearch.yml
        echo "cluster.name: elasticsearch" >> /etc/elasticsearch/elasticsearch.yml
        echo "node.name: elastic-#{i}" >> /etc/elasticsearch/elasticsearch.yml
        echo "discovery.zen.ping.unicast.hosts: #{es_cluster_nodes}"  >> /etc/elasticsearch/elasticsearch.yml
        systemctl restart elasticsearch.service
      SHELL
    end
  end
 
end
