# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version(">=1.9")

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "minimal/xenial64"
  config.vm.hostname = "maven"

  # Configure virtual hardware
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Name in VirtualBox GUI
    vb.name = "maven"
    # Customize the amount of memory on the VM
    vb.memory = "2048"
    # Customize CPUs
    vb.cpus = 2
    # Enable host's resolver as a DNS proxy in NAT mode
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Update virtual box guest additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  
  # Copy maven settings
  config.vm.provision "m2_settings", type: "file", source: "~/.m2/settings.xml", destination: "/home/vagrant/.m2/settings.xml"

  # Provisioning
  config.vm.provision "basics", type: "shell", privileged: true, inline: <<-SHELL
	export DEBIAN_FRONTEND=noninteractive
	apt-get update
	apt-get install -y --no-install-suggests --no-install-recommends openjdk-8-jdk maven git
  SHELL
   
end
